[tool.poetry]
name = "kingdom-rl"
version = "0.1.0"
description = ""
authors = ["Arina <arina.iusupova.ai@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pydirectinput-rgx = "^2.1.2"
pre-commit = "^4.0.1"
numpy = "^2.2.0"
pygetwindow = "^0.0.9"
pyautogui = "^0.9.54"
pillow = "^11.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
