[tool.poetry]
name = "kingdom-rl"
version = "0.1.0"
description = ""
authors = ["Arina <arina.iusupova.ai@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pydirectinput-rgx = "^2.1.2"
pre-commit = "^4.0.1"
numpy = "^2.2.0"
pygetwindow = "^0.0.9"
pyautogui = "^0.9.54"
pillow = "^11.0.0"
keyboard = "^0.13.5"
pynput = "^1.7.7"
torch = {version = "^2.5.1+cu124", source = "pytorch-gpu-src"}
torchvision = {version = "^0.20.1+cu124", source = "pytorch-gpu-src"}
torchaudio = {version = "^2.5.1+cu124", source = "pytorch-gpu-src"}
wandb = "^0.19.4"

[[tool.poetry.source]]
name = "pytorch-gpu-src"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
